GET http://localhost:3000/posts

###

POST http://localhost:4000/token 
Content-Type: application/json

{
    "token": ""
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Smith"
}